### ISSUE TITLE
Use CI/CD Vendor API to capture more context for Spans/Traces 

### ISSUE THREAD

**Issue by dnsmichi** [agardnerIT/tracepusher#38]
## Context 

The experimental New Relic exporter for GitLab query the GitLab REST API using python-gitlab for more data (logs, traces, metrics) and send that data over to an OpenTelemetry endpoint. https://newrelic.com/blog/how-to-relic/monitor-gitlab-with-opentelemetry 

The Newrelic exporters use a post job stage that triggers a child pipeline which then calls the GitLab API to fetch all data and emit to OpenTelemetry (but requires a NewRelic API key). 

## Proposal 

1. Add a `CI_VENDOR` variable that allows to determine which context the script is running in. 
2. Then add `CI_API_ENDPOINT` etc configuration variables as optional. 
3. Fetch additional job log data from the API and attach it to traces/spans 

Not entirely sure if that is possible using the current job before/after script execution model but would be interesting to research.

**Comment by agardnerIT** [comment]
Interesting idea, but I don't like the idea of tracepusher becoming opinionated (or dependent) on specific tooling (Gitlab, New Relic or otherwise). tracepusher should (IMO) stay as tool agnostic as possible. I wouldn't want tracepusher to assume responsibility for keeping up with vendor APIs whenever they change.

Perhaps we could come up with an abstraction layer similar to OpenFeature providers whereby tracepusher can say "go retrieve some data". A provider can then be registered against that "intent" and thus the implementation details can be kept up-to-date by New Relic and tracepusher has a single, standardised interface to "get details" regardless of the backend.

**Comment by agardnerIT** [comment]
@dnsmichi This is getting stale so I'm going to close it. Please re-open if it is still relevant.
